version: "3.1"

services:
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./sql:/docker-entrypoint-initdb.d:ro
      - ./sql/conf.d:/etc/mysql/conf.d:ro
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_USER: blogger
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: goblog
    ports:
      - 9000:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 9001:8080

  go:
    depends_on:
      - mysql
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    ports:
      - 4000:4000

  nginx:
    depends_on:
      - go
      - ui
    image: nginx:1.17
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    volumes:
      - ./nginx/dev:/etc/nginx:ro
    command: /bin/bash -c "nginx -g 'daemon off;'"
    ports:
      - 3000:80

  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile.dev
    volumes:
      - ./ui:/app
      - /app/node_modules
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
      - HTTPS=true
      - SSL_CRT_FILE=/app/tls/cert.pem
      - SSL_KEY_FILE=/app/tls/key.pem
    tty: true
    
